services:

  spring-app:
    container_name: cv-whisper-app
    build: .
    restart: unless-stopped
    ports:
      - "8389:8389"
    networks:
      - kokoro-net

  whisper:
    container_name: cv-whisper
    build: ./whisper-service
    volumes:
      - C:\Users\Alex\.cache\whisper:/root/.cache/whisper
    ports:
      - "5001:5001"
    restart: unless-stopped
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    networks:
      - kokoro-net

networks:
  kokoro-net:
    external: true
